#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# E2E Test Suite: FlowBoard (haiku) — SLAP Project Validation
# ═══════════════════════════════════════════════════════════════
# Validates: route loads, HTML content renders, sections present,
# CSS scoping, reviewer bubbles, popover data, section glow,
# tour walkthrough, ref highlights, slapState integrity.
#
# Generated by /slap-guard
#
# Usage: ./tests/test_flowboard.sh [--port 5173]
# ═══════════════════════════════════════════════════════════════

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/lib/test_utils.sh"

# Parse arguments
[[ "$1" == "--port" ]] && PORT="$2"
[[ "$1" =~ ^[0-9]+$ ]] && PORT="$1"
BASE_URL="http://localhost:$PORT"

setup_cleanup

print_header "FlowBoard (haiku) — SLAP Project E2E Tests"

# ═══════════════════════════════════════════════════════════════
# PREREQ: Server check
# ═══════════════════════════════════════════════════════════════
log_info "PREREQUISITES"

if wait_for_server "$BASE_URL" 10; then
  log_pass "Dev server running at $BASE_URL"
else
  log_fail "Dev server not running at $BASE_URL"
  echo "  Start with: PORT=$PORT npm run dev"
  print_summary
  exit 1
fi

# ═══════════════════════════════════════════════════════════════
# TEST 1: Route loads
# ═══════════════════════════════════════════════════════════════
echo ""
log_info "TEST 1: Route loads"

if open_page "${BASE_URL}/#/flowboard/haiku"; then
  log_pass "Route #/flowboard/haiku opened"
else
  log_fail "Failed to open route"
  print_summary
  exit 1
fi

sleep 2  # Let React render + HTML fetch

# ═══════════════════════════════════════════════════════════════
# TEST 2: HTML content renders
# ═══════════════════════════════════════════════════════════════
echo ""
log_info "TEST 2: HTML content renders"

HAS_CANVAS=$(browser_eval "!!document.querySelector('[data-testid=\"design-html\"]')")
if [ "$HAS_CANVAS" = "true" ]; then
  log_pass "Design canvas element present"
else
  log_fail "Design canvas element not found"
fi

CONTENT_READY=$(browser_eval "window.slapState?.contentReady === true || !!document.querySelector('[data-section=\"hero\"]')")
if [ "$CONTENT_READY" = "true" ]; then
  log_pass "Design content loaded"
else
  log_fail "Design content not loaded"
fi

# ═══════════════════════════════════════════════════════════════
# TEST 3: All 5 sections present in DOM
# ═══════════════════════════════════════════════════════════════
echo ""
log_info "TEST 3: Sections present"

SECTIONS=("hero" "features" "pricing" "testimonials" "cta")
for section in "${SECTIONS[@]}"; do
  HAS_SEC=$(browser_eval "!!document.querySelector('[data-section=\"${section}\"]')")
  if [ "$HAS_SEC" = "true" ]; then
    log_pass "Section [data-section=\"${section}\"] present"
  else
    log_fail "Section [data-section=\"${section}\"] missing"
  fi
done

# ═══════════════════════════════════════════════════════════════
# TEST 4: CSS scoping — design styles don't leak
# ═══════════════════════════════════════════════════════════════
echo ""
log_info "TEST 4: CSS scoping"

# The SLAP UI body font should not be overridden by the design's system font stack
BODY_FONT=$(browser_eval "getComputedStyle(document.body).fontFamily")
DESIGN_FONT=$(browser_eval "(function(){ var el = document.querySelector('[data-section=\"hero\"]'); return el ? getComputedStyle(el).fontFamily : 'none'; })()")

if [ "$BODY_FONT" != "$DESIGN_FONT" ] || [ "$BODY_FONT" = "" ]; then
  log_pass "Design CSS scoped — body font differs from design font"
else
  # Both using same font could be coincidence — check for scoping wrapper
  HAS_SCOPE=$(browser_eval "!!document.querySelector('.slap-design')")
  if [ "$HAS_SCOPE" = "true" ]; then
    log_pass "Design CSS scoped under .slap-design wrapper"
  else
    log_fail "CSS scoping missing — no .slap-design wrapper"
  fi
fi

# ═══════════════════════════════════════════════════════════════
# TEST 5: All 13 reviewer bubbles on rail
# ═══════════════════════════════════════════════════════════════
echo ""
log_info "TEST 5: Reviewer bubbles"

REVIEWERS=("marketing" "ux" "product" "technical" "design" "frank" "elena" "carlos" "jasmine" "sam" "sarah" "dorothy" "mike")
BUBBLE_COUNT=0
for reviewer in "${REVIEWERS[@]}"; do
  HAS_BUBBLE=$(browser_eval "!!document.querySelector('[data-testid=\"draft-slot-${reviewer}\"]')")
  if [ "$HAS_BUBBLE" = "true" ]; then
    BUBBLE_COUNT=$((BUBBLE_COUNT + 1))
  fi
done

if [ "$BUBBLE_COUNT" -eq 13 ]; then
  log_pass "All 13 reviewer bubbles present on rail"
else
  log_fail "Reviewer bubbles" "Found $BUBBLE_COUNT/13"
  # Report which are missing
  for reviewer in "${REVIEWERS[@]}"; do
    HAS=$(browser_eval "!!document.querySelector('[data-testid=\"draft-slot-${reviewer}\"]')")
    if [ "$HAS" != "true" ]; then
      log_info "  Missing: $reviewer"
    fi
  done
fi

# ═══════════════════════════════════════════════════════════════
# TEST 6: Popover shows score and verdict
# ═══════════════════════════════════════════════════════════════
echo ""
log_info "TEST 6: Popover data"

click_testid "draft-slot-marketing"
sleep 0.5

POPOVER_TEXT=$(browser_eval "document.querySelector('[data-testid=\"bubble-popover\"]')?.textContent || ''")

if echo "$POPOVER_TEXT" | grep -q "/10"; then
  log_pass "Popover shows score (/10)"
else
  log_fail "Popover score missing" "No /10 in popover"
fi

if echo "$POPOVER_TEXT" | grep -qi "marketing\|MARKETING"; then
  log_pass "Popover shows reviewer name"
else
  log_fail "Popover reviewer name missing"
fi

# Short verdict should be present
if echo "$POPOVER_TEXT" | grep -qi "generic\|template\|SaaS"; then
  log_pass "Popover shows short verdict content"
else
  log_skip "Short verdict content not detected (may use different keywords)"
fi

# Close popover
click_testid "draft-backdrop"
sleep 0.3

# ═══════════════════════════════════════════════════════════════
# TEST 7: Section glow on finding hover
# ═══════════════════════════════════════════════════════════════
echo ""
log_info "TEST 7: Section glow"

click_testid "draft-slot-marketing"
sleep 0.5
click_testid "popover-view-full"
sleep 0.5

# Hover a finding in the panel
FINDING_EXISTS=$(browser_eval "!!document.querySelector('[data-testid=\"panel-finding-hero-0\"]')")
if [ "$FINDING_EXISTS" = "true" ]; then
  browser_eval "(function(){ var f = document.querySelector('[data-testid=\"panel-finding-hero-0\"]'); if(f) { f.dispatchEvent(new PointerEvent('pointerenter', {bubbles:false})); f.dispatchEvent(new MouseEvent('mouseover', {bubbles:true})); } })()"
  sleep 0.5

  HL=$(browser_eval "window.slapState?.highlightedSection")
  if [ "$HL" = "hero" ]; then
    log_pass "Finding hover highlights hero section"
  else
    # React may not respond to programmatic events
    log_skip "Glow trigger needs real pointer (programmatic dispatch limited)"
  fi
else
  log_skip "Panel finding hero-0 not found"
fi

# Close panel
click_testid "review-panel-close"
sleep 0.3

# ═══════════════════════════════════════════════════════════════
# TEST 8: Tour starts and walks sections
# ═══════════════════════════════════════════════════════════════
echo ""
log_info "TEST 8: Tour mode"

# Start tour
click_testid "draft-tour-btn"
sleep 1

TOUR_ACTIVE=$(browser_eval "window.slapState?.tourActive")
if [ "$TOUR_ACTIVE" = "true" ]; then
  log_pass "Tour started"
else
  log_fail "Tour did not start"
fi

# Check first section is spotlighted
SPOT_SECTION=$(browser_eval "window.slapState?.tourSection")
if [ "$SPOT_SECTION" = "hero" ]; then
  log_pass "Tour starts on hero section"
else
  log_fail "Tour start section" "Expected hero, got: $SPOT_SECTION"
fi

# Step through sections
EXPECTED=("features" "pricing" "testimonials" "cta")
TOUR_PASS=true
for next_section in "${EXPECTED[@]}"; do
  click_testid "tour-next"
  sleep 0.5
  CURRENT=$(browser_eval "window.slapState?.tourSection")
  if [ "$CURRENT" = "$next_section" ]; then
    log_pass "Tour stepped to: $next_section"
  else
    log_fail "Tour step" "Expected $next_section, got: $CURRENT"
    TOUR_PASS=false
    break
  fi
done

# End tour
click_testid "tour-next"
sleep 0.5
TOUR_DONE=$(browser_eval "window.slapState?.tourActive")
if [ "$TOUR_DONE" = "false" ]; then
  log_pass "Tour completed (tourActive=false)"
else
  log_skip "Tour may loop or remain active"
fi

# ═══════════════════════════════════════════════════════════════
# TEST 9: Ref highlights
# ═══════════════════════════════════════════════════════════════
echo ""
log_info "TEST 9: Ref highlights"

# Key data-ref elements should exist in the DOM
REFS=("hero-headline" "hero-cta" "features-headline" "tier-pro" "cta-headline")
REF_COUNT=0
for ref in "${REFS[@]}"; do
  HAS_REF=$(browser_eval "!!document.querySelector('[data-ref=\"${ref}\"]')")
  if [ "$HAS_REF" = "true" ]; then
    REF_COUNT=$((REF_COUNT + 1))
  fi
done

if [ "$REF_COUNT" -eq ${#REFS[@]} ]; then
  log_pass "All ${#REFS[@]} sampled data-ref elements found in DOM"
else
  log_fail "Ref elements" "Found $REF_COUNT/${#REFS[@]} sampled refs"
fi

# ═══════════════════════════════════════════════════════════════
# TEST 10: slapState integrity
# ═══════════════════════════════════════════════════════════════
echo ""
log_info "TEST 10: slapState"

STATE_PROJECT=$(browser_eval "window.slapState?.project")
if [ "$STATE_PROJECT" = "flowboard" ]; then
  log_pass "slapState.project = flowboard"
else
  log_fail "slapState.project" "Expected flowboard, got: $STATE_PROJECT"
fi

STATE_VERSION=$(browser_eval "window.slapState?.version")
if [ "$STATE_VERSION" = "haiku" ]; then
  log_pass "slapState.version = haiku"
else
  log_fail "slapState.version" "Expected haiku, got: $STATE_VERSION"
fi

STATE_SECTIONS=$(browser_eval "JSON.stringify(window.slapState?.sections)")
if echo "$STATE_SECTIONS" | grep -q "hero" && echo "$STATE_SECTIONS" | grep -q "testimonials"; then
  log_pass "slapState.sections contains hero and testimonials"
else
  log_fail "slapState.sections" "Got: $STATE_SECTIONS"
fi

# ═══════════════════════════════════════════════════════════════
# TEST 11: Persona-specific popover checks (sample 3)
# ═══════════════════════════════════════════════════════════════
echo ""
log_info "TEST 11: Persona popover spot-checks"

# Frank — score should be 3.5
click_testid "draft-slot-frank"
sleep 0.5
FRANK_TEXT=$(browser_eval "document.querySelector('[data-testid=\"bubble-popover\"]')?.textContent || ''")
if echo "$FRANK_TEXT" | grep -q "3.5"; then
  log_pass "Frank score 3.5 in popover"
else
  log_fail "Frank score" "Expected 3.5 in popover"
fi
click_testid "draft-backdrop"
sleep 0.3

# Sarah — score should be 3.0
click_testid "draft-slot-sarah"
sleep 0.5
SARAH_TEXT=$(browser_eval "document.querySelector('[data-testid=\"bubble-popover\"]')?.textContent || ''")
if echo "$SARAH_TEXT" | grep -q "3.0"; then
  log_pass "Sarah score 3.0 in popover"
else
  log_fail "Sarah score" "Expected 3.0 in popover"
fi
click_testid "draft-backdrop"
sleep 0.3

# Technical — score should be 6.8
click_testid "draft-slot-technical"
sleep 0.5
TECH_TEXT=$(browser_eval "document.querySelector('[data-testid=\"bubble-popover\"]')?.textContent || ''")
if echo "$TECH_TEXT" | grep -q "6.8"; then
  log_pass "Technical score 6.8 in popover"
else
  log_fail "Technical score" "Expected 6.8 in popover"
fi
click_testid "draft-backdrop"
sleep 0.3

# ═══════════════════════════════════════════════════════════════
# TEST 12: Panel findings per section
# ═══════════════════════════════════════════════════════════════
echo ""
log_info "TEST 12: Panel findings structure"

click_testid "draft-slot-marketing"
sleep 0.5
click_testid "popover-view-full"
sleep 0.5

# Check findings exist for multiple sections
for section in "hero" "features" "pricing" "testimonials" "cta"; do
  HAS=$(browser_eval "!!document.querySelector('[data-testid=\"panel-finding-${section}-0\"]')")
  if [ "$HAS" = "true" ]; then
    log_pass "Marketing has findings for section: $section"
  else
    log_fail "Marketing missing findings for: $section"
  fi
done

click_testid "review-panel-close"
sleep 0.3

# ═══════════════════════════════════════════════════════════════
# CLEANUP
# ═══════════════════════════════════════════════════════════════
echo ""
log_info "CLEANUP"

agent-browser close 2>/dev/null
log_pass "Browser closed"

# ═══════════════════════════════════════════════════════════════
# SUMMARY
# ═══════════════════════════════════════════════════════════════
print_summary
exit $?
